import pandas as pd

data = [('2nd row armrest', 'w', 'null', 'XD2材料', '2ND ROW SEAT', 'X03_SEAT'),
        ('2ND ROW HEATED SEAT', 'w,w/o', 'null', 'XX4SC', '2ND ROW SEAT', 'X03_SEAT'),
        ('2ND ROW SEAT COMFORT FEATURE', 'ALL', 'null', 'XX4EMC', '2ND ROW SEAT', 'X03_SEAT'),
        ('2ND ROW SEAT HEATER AND COOLER', 'ALL', 'null', 'XX4EMC', '2ND ROW SEAT', 'X03_SEAT'),
        ('2ND ROW SEAT TYPE AND ADJUSTMENT', 'ALL', 'null', 'XX4EMC', '2ND ROW SEAT', 'X03_SEAT'),
        ('2ND ROW SEAT TYPE AND ADJUSTMENT.', 'BENCH,SPRIT', 'null', 'XR6シートベルト', '2ND ROW SEAT', 'X03_SEAT'),
        ('CENTER CONSOLE 2ND ROW', '2ND SUPER MULTI CONSOLE with RCP', 'null', 'XX4EMC', '2ND ROW SEAT', 'X03_SEAT'),
        ('REAR SEAT', 'ALL', 'null', 'XR2車体信頼', '2ND ROW SEAT', 'X03_SEAT'),
        ('REAR SEAT ALERT', 'ALL', 'null', 'XR6乗員判別,XX4EMC', '2ND ROW SEAT', 'X03_SEAT'),
        ('Rr Heater Seat', 'with', 'null', 'XR5空調', '2ND ROW SEAT', 'X03_SEAT'),
        ('RR SEAT HEATER', 'Ｗ', 'null', 'XX4WH', '2ND ROW SEAT', 'X03_SEAT'),
        ('RR SEAT HEATER AND COOLER', 'Ｗ', 'null', 'XX4WH', '2ND ROW SEAT', 'X03_SEAT'),
        ('Rr 空調シート(Heater ＋ Cooler Seat)', 'with', 'null', 'XR5空調', '2ND ROW SEAT', 'X03_SEAT'),
        ('後席ODS仕様', 'with,without', 'null', 'XR6シートベルト', '2ND ROW SEAT', 'X03_SEAT'),
        ('後席シートスライド', 'with,without', 'null', 'XR6シートベルト', '2ND ROW SEAT', 'X03_SEAT'),
        ('後席シートリクライニング', 'with,without', 'null', 'XR6シートベルト', '2ND ROW SEAT', 'X03_SEAT'),
        ('Central door locking', 'central door lock SW (DR)', 'null', 'XX4スイッチ', 'ACCESS', 'X08_EXTERIOR'),
        ('DOOR SAFETY', 'ALL', 'null', 'XX4EMC', 'ACCESS', 'X08_EXTERIOR'),
        ('FLUSH DOOR HANDLE', 'w', 'null', 'XX4メカトロS45', 'ACCESS', 'X08_EXTERIOR'),
        ('Flush handle', 'w,w/o', 'null', 'XX4BCM', 'ACCESS', 'X08_EXTERIOR'),
        ('I-KEY ', 'ALL', 'null', 'XX4EMC', 'ACCESS', 'X08_EXTERIOR'),
        ('I-KEY (BADGE)', 'ALL', 'null', 'XX4EMC', 'ACCESS', 'X08_EXTERIOR'),
        ('Panic Alarm', 'w,w/o', 'null', 'XX4BCM', 'ACCESS', 'X08_EXTERIOR'),
        ('SAFETY ACCESS FUNCTIONS', 'ALL', 'null', 'XX4EMC', 'ACCESS', 'X08_EXTERIOR'),
        ('Speed sensing lock', 'w,w/o', 'null', 'XX4BCM', 'ACCESS', 'X08_EXTERIOR'),
        ('Touch Sensor  (I-key)', 'w,w/o', 'null', 'XX4BCM', 'ACCESS', 'X08_EXTERIOR'),
        ('通常のグリップ型アウトサイドハンドル、マニュアルヒドゥンハンドル', 'null', 'null', 'XX4Flush', 'ACCESS', 'X08_EXTERIOR'),
        ('電動格納式フラッシュアウトサイドハンドル付', 'null', 'null', 'XX4Flush', 'ACCESS', 'X08_EXTERIOR'),
        ('AD', 'w', 'null', 'XR6視界,XP4EVシステム', 'ADAS COMFORT', 'X11_SAFETY_SECURITY'),
        ('AD(AUTONOMOUS DRIVING)', 'ALL', 'null', 'XX4WH', 'ADAS COMFORT', 'X11_SAFETY_SECURITY'),
        ('AD1', 'w,w/o', 'null', 'XX4GN1ラジオノイズ', 'ADAS COMFORT', 'X11_SAFETY_SECURITY'),
        (
            'AD2', 'w,w/o', 'null', 'XJBVDC,XQ5Failsafe,XX4GN1ラジオノイズ,XM6アンテナ,XX4AD', 'ADAS COMFORT',
            'X11_SAFETY_SECURITY'),
        ('ADAPTIVE CRUISE CONTROL (ACC)', 'ALL,w', 'null', 'XX4EMC,XX4WH', 'ADAS COMFORT', 'X11_SAFETY_SECURITY'),
        ('ASCD', 'w', 'オートスピードコントロール', 'UE2動力運転性,XP4EVシステム', 'ADAS COMFORT', 'X11_SAFETY_SECURITY'), (
            'AUTONOMOUS DRIVING', 'ALL,w/o,AD1,AD2', 'null',
            'XX4EMC,XM6メータ,UE2燃費,XX4EMC,XQ3AD,XX4CANGateway,XX4BCM,XX4EMC,XX4PT,XX4SV,XX4EMC,XX4PT', 'ADAS COMFORT',
            'X11_SAFETY_SECURITY'), (
            'AUTONOMOUS DRIVING SF', 'AD2 ✚ INFORMATION SUPPORT LIGHT AD LINK', 'null', 'XX4EMC', 'ADAS COMFORT',
            'X11_SAFETY_SECURITY'), ('CRUISE CONTROL', 'ALL', 'null', 'XX4EMC', 'ADAS COMFORT', 'X11_SAFETY_SECURITY'),
        ('CRUISE CONTROL/SPEED LIMI', 'null', 'null', 'XQ3AD', 'ADAS COMFORT', 'X11_SAFETY_SECURITY'),
        ('CRUISE CONTROL/SPEED LIMITER', 'ALL', 'null', 'XX4EMC', 'ADAS COMFORT', 'X11_SAFETY_SECURITY'),
        ('DRIVING ASSITANCE', 'ALL', 'null', 'XX4EMC', 'ADAS COMFORT', 'X11_SAFETY_SECURITY'),
        ('ICC', 'w,w/o', 'null', 'XJBVDC', 'ADAS COMFORT', 'X11_SAFETY_SECURITY'),
        ('ICC(ｲﾝﾃﾘｼﾞｪﾝﾄ ｸﾙｰｽﾞ ｺﾝﾄﾛｰﾙ)', 'null', 'null', 'XQ4機構', 'ADAS COMFORT', 'X11_SAFETY_SECURITY'), (
            'Safety Driving', 'ACC,ICC,AD1,AD1e,AD1+Navilink,AD1e+Navilink', 'null', 'XX4AD', 'ADAS COMFORT',
            'X11_SAFETY_SECURITY'), ('SPEED LIMITER', 'ALL', 'null', 'XX4EMC', 'ADAS COMFORT', 'X11_SAFETY_SECURITY'),
        ('プロパイロット', 'null', 'AD1,AD2', 'XQA商品性', 'ADAS COMFORT', 'X11_SAFETY_SECURITY'),
        ('AROUND VIEW MONITOR\n（AVM）', 'ALL', 'null', 'XR6視界', 'ADAS PARKING', 'X11_SAFETY_SECURITY'), (
            'AROUND VIEW MONITOR', 'ALL,w', 'null', 'XX4EMC,XQ3AD,XX4GN1ラジオノイズ,XX4WH,XM6camera', 'ADAS PARKING',
            'X11_SAFETY_SECURITY'), ('FAP（フルオートパーク）', 'w', 'null', 'UI6EV', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('FR CAMERA', 'w,w/o', 'null', 'XL7外装,XR6内外装', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('FR RADAR', 'null', 'null', 'XL7外装', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('FR SIDE CAMERA', 'null', 'null', 'XL7外装', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('FR SIDE RADAR', 'null', 'null', 'XL7外装', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('FR SONAR', 'null', 'null', 'XL7外装', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('Full FlanK Protection(FKP)', 'w', 'null', 'XX4SONAR', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('MOVING OBJECT DETECTION (MOD)', 'null', 'null', 'XQ3AD', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('OUTSIDE CAMERA', 'ALL', 'null', 'XX4EMC', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('PARK ASSIST', 'ALL', 'null', 'XX4EMC', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('PARKING ALERTS', 'ALL', 'null', 'XX4EMC', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('PARKING ASSIST SYSTEM', 'ALL', 'null', 'XQ3AD,XX4EMC', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('PROXIMITY RADAR', 'ALL', 'null', 'XX4EMC', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('REAR CAMERA', 'w', 'null', 'XX4GN1ラジオノイズ', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('REAR VIEW CAMERA', 'ALL', 'null', 'XX4EMC,XM6camera', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('REAR VIEW MONITOR\n（RVM）', 'ALL', 'null', 'XR6視界', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('REMOTE PARKING', 'w,w/o,ALL', 'null', 'XX4BCM,XX4EMC', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('RR CAMERA', 'w,w/o', 'null', 'XL7外装,XR6内外装', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('RR SIDE RADAR', 'null', 'null', 'XL7外装', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('RR SONAR', 'null', 'null', 'XL7外装', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('SONER', 'ALL', 'null', 'XX4EMC', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        ('プロパイロットパーク', 'null', 'null', 'XQA商品性', 'ADAS PARKING', 'X11_SAFETY_SECURITY'),
        (' LANE DEPARTURE PREVENTION (LDP)', 'null', 'null', 'XQ3AD', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('ADAPTIVE DRIVING BEAM (ADB)', 'w,w/o', 'null', 'XR6視界,XX4LEDHead', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('AFS', 'null', 'アダプティブフロントライティングシステム', 'XR6視界', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('AUTOMATIC EMERGENCY BRAKING SYSTEM  (AEBS)', 'ALL', 'null', 'XX4EMC', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('AUTONOMOUS EMERGENCY STEERING', 'ALL', 'null', 'XX4EMC', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('AUTONOMOUS EMERGENCY STEERING (AES)', 'ALL', 'null', 'XX4EMC', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('BACKWARD COLLISION PREVEN', 'ALL', 'null', 'XX4EMC', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('BLIND SPOT DETECTION', 'ALL', 'null', 'XX4EMC', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('BLIND SPOT INTERVENTION (BSI)', 'null', 'null', 'XQ3AD', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('BLIND SPOT WARNING (BSW)', 'null', 'null', 'XQ3AD', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('CITY ✚ REAR CROSS TRAFFIC ALERT (RCTA)', 'null', 'null', 'XQ3AD', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('DRIVE EVENT RECORDER', 'ALL', 'null', 'XX4EMC', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('DRIVE RECORDER', 'w,w/o', 'null', 'XX4GN1ラジオノイズ,XX4CANGateway', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('DRIVER MONITORING', 'ALL', 'null', 'XX4EMC', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('driver monitoring by steering', 'null', 'null', 'XQ3AD', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('DVR', 'null', 'ドライブレコーダー', 'XR6視界,XX4DVR', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('EMERGENCY ASSIST FOR PEDAL MISAPPLICATION', 'ALL', 'null', 'XQ3AD,XX4EMC', 'ADAS SAFETY',
         'X11_SAFETY_SECURITY'),
        ('emergency steering assist/support (esa/ess)', 'null', 'null', 'XQ3AD', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('ESS', 'null', 'EMERGENCY STEERING ASSIST/SUPPORT (ESA/ESS)', 'XR6視界', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('FORWARD COLLISION WARNING', 'ALL', 'null', 'XX4EMC', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('FORWARD EMERGENCY BRAKING', 'ALL', 'null', 'XQ3AD,XX4EMC,XX4AD', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('FRONT COLLISION WARNING', 'null', 'null', 'XQ3AD', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('LANE DEPARTURE WARNING (LDW)', 'null', 'null', 'XQ3AD', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('LANE KEEP', 'ALL', 'null', 'XQ3AD,XX4EMC', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('LATERAL SUPPORT SYSTEM', 'ALL', 'null', 'XX4EMC', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('OCCUPANT MONITORING', 'ALL', 'null', 'XX4EMC', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('OCCUPANTS SAFE EXIT', 'ALL', 'null', 'XX4EMC', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('predictive forward collision warning (pfcw)', 'null', 'null', 'XQ3AD', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('REAR AEB', 'null', 'null', 'XQ3AD', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('SCENE RECORDER', 'ALL', 'null', 'XX4EMC', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('TRAFFIC SIGN RECOGNITION', 'ALL', 'null', 'XX4EMC', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'),
        ('TRAFFIC SIGN RECOGNITION (TSR)', 'null', 'null', 'XQ3AD', 'ADAS SAFETY', 'X11_SAFETY_SECURITY'), (
            'TRAFFIC SIGN RECOGNITION / SPEED LIMITATION INFORMATION', 'ALL', 'null', 'XX4EMC', 'ADAS SAFETY',
            'X11_SAFETY_SECURITY'),
        ('AIR CONDITIONER', 'AUTO A/C,ALL', 'null', 'XR5空調,XX4SC', 'AIR CONDITIONING AND HEATING',
         'X06_AIR_CONDITIONER'), (
            'AIR CONDITIONING AND HEATING SYSTEM', 'ALL', 'null', 'XX4EMC,XQE電動車', 'AIR CONDITIONING AND HEATING',
            'X06_AIR_CONDITIONER'), (
            'AIR CONDITIONING AND HEATING TYPE', 'ALL', 'null', 'XX4NH電動車,XX4EMC,XX4WH',
            'AIR CONDITIONING AND HEATING',
            'X06_AIR_CONDITIONER'),
        ('AIR CONTIONING AND HEATIN', 'ALL', 'null', 'XX4EMC', 'AIR CONDITIONING AND HEATING', 'X06_AIR_CONDITIONER'), (
            'BATTERY HEATING', '(Water PTC),w', 'null', 'XX4NH電動車,XQ5保安防災', 'AIR CONDITIONING AND HEATING',
            'X06_AIR_CONDITIONER'),
        ('FULL AUTO A/C (TOUCH PANEL TYPE)', 'ALL', 'null', 'XX4EMC', 'AIR CONDITIONING AND HEATING',
         'X06_AIR_CONDITIONER'),
        ('HEAT PUMP', 'w,w/o', 'null', 'XR5空調', 'AIR CONDITIONING AND HEATING', 'X06_AIR_CONDITIONER'),
        ('HEATER FOR EV', '(AIR PTC)', 'null', 'XX4NH電動車', 'AIR CONDITIONING AND HEATING', 'X06_AIR_CONDITIONER'),
        ('HEATER FOR EV / ADDITIONAL HEATER', 'ALL', 'null', 'XX4EMC', 'AIR CONDITIONING AND HEATING',
         'X06_AIR_CONDITIONER'),
        ('PTC Heater', 'w,w/o', 'null', 'XX4BCM', 'AIR CONDITIONING AND HEATING', 'X06_AIR_CONDITIONER'),
        ('AIR TREATMENT', 'ALL', 'null', 'XX4EMC', 'AIR QUALITY MANAGEMENT', 'X06_AIR_CONDITIONER'),
        ('AIRBAG CANCEL', 'ALL', 'null', 'XX4EMC', 'AIRBAGS', 'X11_SAFETY_SECURITY'),
        ("DRIVER'S AIRBAG", 'ALL', 'null', 'XX4EMC', 'AIRBAGS', 'X11_SAFETY_SECURITY'),
        ('FAR SIDE AIRBAG', 'ALL', 'null', 'XX4EMC', 'AIRBAGS', 'X11_SAFETY_SECURITY'),
        ('FRONT AIRBAG', 'ALL', 'null', 'XX4EMC', 'AIRBAGS', 'X11_SAFETY_SECURITY'),
        ('FRONT KNEE AIRBAGS', 'ALL', 'null', 'XX4EMC', 'AIRBAGS', 'X11_SAFETY_SECURITY'),
        ('FRONT SIDE AIRBAG', 'ALL', 'null', 'XX4EMC', 'AIRBAGS', 'X11_SAFETY_SECURITY'),
        ('PASSENGER AIRBAG', 'ALL', 'null', 'XX4EMC', 'AIRBAGS', 'X11_SAFETY_SECURITY'),
        ('SIDE AIRBAG', 'ALL', 'null', 'XX4EMC', 'AIRBAGS', 'X11_SAFETY_SECURITY'),
        ('SIDE CURTAIN AIRBAG', 'ALL', 'null', 'XX4EMC', 'AIRBAGS', 'X11_SAFETY_SECURITY'), (
            'Ambient light', 'Mono color ambient,Multi color', 'null', 'XX4ESS49', 'AMBIENT LIGHTING',
            'X04_INTERIOR_TRIM_&_STORAGE'),
        ('Ambient lighting', 'マルチカラー,モノかラー', 'null', 'XX4BCM', 'AMBIENT LIGHTING', 'X04_INTERIOR_TRIM_&_STORAGE'),
        ('ZONES OF AMBIENT LIGHTING', 'ALL', 'null', 'XX4EMC', 'AMBIENT LIGHTING', 'X04_INTERIOR_TRIM_&_STORAGE'),
        ('SOCKET ACCESSORY', 'ALL', 'null', 'XX4EMC', 'AMENITY', 'X05_AMENITY'),
        ('USB AND POWER SUPPLY', 'w_1500W,wo_1500W', 'null', 'XX4NH電動車BATTERY HEATING', 'AMENITY', 'X05_AMENITY'),
        ('USB AND POWER SUPPLY 2ND ROW', 'ALL', 'null', 'XX4EMC', 'AMENITY', 'X05_AMENITY'),
        ('USB AND POWER SUPPLY 3RD ROW', 'ALL', 'null', 'XX4EMC', 'AMENITY', 'X05_AMENITY'),
        ('USB AND POWER SUPPLY FR', 'ALL', 'null', 'XX4EMC', 'AMENITY', 'X05_AMENITY'),
        ('USB AND POWER SUPPLY LUGGAGE', 'ALL', 'null', 'XX4EMC', 'AMENITY', 'X05_AMENITY'),
        ('WIRELESS PHONE CHARGE', 'ALL', 'null', 'XX4EMC', 'AMENITY', 'X05_AMENITY'),
        ('AS HEATED SEAT', 'w,w/o', 'null', 'XX4SC', 'ASSIST SEAT', 'X03_SEAT'),
        ('AS SEAT COMFORT FEATURE', 'ALL', 'null', 'XX4EMC', 'ASSIST SEAT', 'X03_SEAT'),
        ('AS SEAT HEATER ', 'w,w/o', 'null', 'XR6乗員判別', 'ASSIST SEAT', 'X03_SEAT'),
        ('AS SEAT HEATER AND COOLER', 'ALL', 'null', 'XX4EMC', 'ASSIST SEAT', 'X03_SEAT'),
        ('AS SEAT TYPE AND ADJUSTMENT', 'ALL', 'null', 'XX4EMC', 'ASSIST SEAT', 'X03_SEAT'),
        ('AS SEAT TYPE AND ADJUSTMENT.', 'POWER,MANUAL', 'null', 'XR6シートベルト', 'ASSIST SEAT', 'X03_SEAT'),
        ('FRONT PASSENGER SEAT(S)', 'ALL', 'null', 'XX4EMC', 'ASSIST SEAT', 'X03_SEAT'),
        ('OCCUPANT MONITORING / CHILD PRESENCE DETECTION DIRECT', 'null', 'null', 'XR6乗員判別', 'ASSIST SEAT',
         'X03_SEAT'),
        ('OCCUPANT MONITORING / CHILD PRESENCE DETECTION INDIRECT', 'null', 'null', 'XR6乗員判別', 'ASSIST SEAT',
         'X03_SEAT'),
        ('助手席SEN仕様', '歪み式,静電容量式,簡易マット式', 'null', 'XR6シートベルト', 'ASSIST SEAT', 'X03_SEAT'), ('ANTENNA',
                                                                                                          '200mm ROD,300mm ROD,800mm ROD,PILLAR,COWL TOP,SHARK FIN,ON GLASS\n(SIDE),ON GLASS\n(REAR),ON GLASS\n(BACK DOOR)',
                                                                                                          'null',
                                                                                                          'XM6アンテナ',
                                                                                                          'AUDIO & NAVIGATION',
                                                                                                          'X07_AUDIO_NAVIGATION_CCS'),
        ('AUDIO', 'IVI,DA,レス', 'null', 'XM6音質,XX4AD', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('AUDIO & NAVIGATION', 'ALL', 'null', 'XX4WH', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('AUDIO & NAVIGATION / TYPES OF RADIOS', 'ALL', 'null', 'XM6アンテナ', 'AUDIO & NAVIGATION',
         'X07_AUDIO_NAVIGATION_CCS'),
        ('AUDIO LESS', 'w', 'null', 'XX4GN1ラジオノイズ', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('Audio Navigation', 'GAS NAVI,DA', 'null', 'XX4SV', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('CCS2', 'w', 'null', 'XM6E2E', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('DISPLAY AUDIO', 'w', 'null', 'XX4GN1ラジオノイズ,XR4HMI', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('GALASS ANTENNA', 'w', 'null', 'XX4GN1ラジオノイズ', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('HEAD UNIT', 'NAVI,AUDIO,AUDIO LESS,NAVI READY', 'null', 'XM6アンテナ', 'AUDIO & NAVIGATION',
         'X07_AUDIO_NAVIGATION_CCS'),
        ('IVI', 'w,w/o', 'null', 'XX4BCM,XM6IVI,XR4HMI', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('IVI（NAVI/DA）', 'NAVI,DA,Less', 'null', 'XM6メータ', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('LOCAL NAVI', 'w', 'null', 'XX4GN1ラジオノイズ', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('NAVI', 'w', 'null', 'XX4GN1ラジオノイズ', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('Navi-size', 'ALL', 'null', 'XR6内外装', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('REAR VIDEO SCREENS', 'ALL', 'null', 'XX4EMC', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('ROD ANTENNA', 'w', 'null', 'XX4GN1ラジオノイズ', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('SHARK FIN ANTENNA', 'w', 'null', 'XX4GN1ラジオノイズ', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('TYPE OF HEAD UNIT HARDWARE & CCS SF', 'ALL', 'null', 'XX4EMC', 'AUDIO & NAVIGATION',
         'X07_AUDIO_NAVIGATION_CCS'), (
            'TYPES OF RADIOS', 'DA,NAVI,GAS NAVI,ALL', 'null', 'XX4CANGateway,XX4EMC', 'AUDIO & NAVIGATION',
            'X07_AUDIO_NAVIGATION_CCS'),
        ('VIDEO SCREENS', 'ALL', 'null', 'XX4EMC', 'AUDIO & NAVIGATION', 'X07_AUDIO_NAVIGATION_CCS'),
        ('ANTI-LOCK BRAKING SYSTEM', 'ALL', 'null', 'XX4EMC', 'BRAKING', 'X09_MECHANISM'),
        ('BRAKING ASSISTANCE', 'ALL', 'null', 'XX4EMC', 'BRAKING', 'X09_MECHANISM'),
        ('EMERGENCY BRAKE ASSIST (EBA / BA)', 'ALL', 'null', 'XX4EMC', 'BRAKING', 'X09_MECHANISM'),
        ('RR BRAKE UNIT', 'null', 'null', 'XR2コントロール', 'BRAKING', 'X09_MECHANISM'),
        ('VDC', 'ALL', 'null', 'XX4EMC', 'BRAKING', 'X09_MECHANISM'),
        ('VDC(ﾋﾞｰｸﾙ ﾀﾞｲﾅﾐｸｽ ｺﾝﾄﾛｰﾙ)', 'null', 'null', 'XQ4機構', 'BRAKING', 'X09_MECHANISM'),
        ('AC 120V or 240V 1500W OUTLET', 'Ｗ', 'null', 'XX4WH', 'CHARGER', 'X14_EV_PHEV_HEV'),
        ('AC CHARGER', 'null', 'null', 'XX4EMC', 'CHARGER', 'X14_EV_PHEV_HEV'), (
            'AC PLUG STANDARD', 'MODE 2 CABLE\n100V/120V,MODE 2 CABLE\n200V /230V/240V,MODE 3 CABLE ', 'null',
            'XX4EMC,XX4NH電動車', 'CHARGER', 'X14_EV_PHEV_HEV'),
        ('Battery Charger For ELEC. VEH', 'ALL', 'null', 'UE2燃費', 'CHARGER', 'X14_EV_PHEV_HEV'),
        ('CHARGER', 'SINGLE,3PHASE', 'null', 'XX4NH電動車', 'CHARGER', 'X14_EV_PHEV_HEV'),
        ('DC CHARGER', 'null', 'null', 'XX4EMC', 'CHARGER', 'X14_EV_PHEV_HEV'),
        ('PLUG AND CHARGE', 'null', 'null', 'XX4EMC', 'CHARGER', 'X14_EV_PHEV_HEV'),
        ('REVERSIBLE CHARGER', 'VEHICLE TO LOAD (V2L) OUTSIDE', 'null', 'XX4NH電動車,XX4EMC', 'CHARGER',
         'X14_EV_PHEV_HEV'),
        ('VEHICLE TO LOAD (V2L) OUTSIDE', 'w', 'null', 'XP4充電', 'CHARGER', 'X14_EV_PHEV_HEV'),
        ('三相(AC3)', 'AC3', 'null', 'XX4HF-VR-ETC', 'CHARGER', 'X14_EV_PHEV_HEV'),
        ('単相(AC1)', 'AC1', 'null', 'XX4HF-VR-ETC', 'CHARGER', 'X14_EV_PHEV_HEV'),
        ('COMBI METER', 'FULL TFT,ANALOG SPEED+TACHO + TFT,ALL', 'null', 'XX4CANGateway', 'COMBI METER', 'X02_COCKPIT'),
        ('Head Up Display', 'w,w/o', 'null', 'XX4SV', 'COMBI METER', 'X02_COCKPIT'),
        ('HEAD UP DISPLAY (HUD)', 'ALL', 'null', 'XX4EMC,XX4WH,XX4CANGateway', 'COMBI METER', 'X02_COCKPIT'),
        ('HUD', 'w,w/o', 'null', 'XR4HMI,XX4GN1ラジオノイズ,XM6メータ,XX4AD', 'COMBI METER', 'X02_COCKPIT'),
        ('Meter', 'Full TFT,Display,Segment', 'null', 'XX4BCM,XX4AD', 'COMBI METER', 'X02_COCKPIT'),
        ('Meter Display Size', '7inch,12.3inch,14inch', 'null', 'XX4SV,XX4AD', 'COMBI METER', 'X02_COCKPIT'),
        ('METER UNIT', 'ALL', 'null', 'XX4EMC', 'COMBI METER', 'X02_COCKPIT'),
        ('SETTINGS OF COMBI METER', 'ALL', 'null', 'XX4EMC,XR6シートベルト', 'COMBI METER', 'X02_COCKPIT'),
        ('SIZE OF COMBI METER SCREEN', 'ALL,14.3" DISPLAY', 'null', 'XX4EMC,XM6メータ,XR6シートベルト', 'COMBI METER',
         'X02_COCKPIT'),
        ('SPEED METER UNIT', 'ALL', 'null', 'XX4EMC', 'COMBI METER', 'X02_COCKPIT'),
        ('TYPE OF COMBI METER', 'ALL,FULL TFT', 'null', 'XX4EMC,XR6シートベルト', 'COMBI METER', 'X02_COCKPIT'),
        ('2nd Seat\n3rd Seat', 'w/o', 'null', 'XQ2乗心地性能', 'DRIVER SEAT', 'X03_SEAT'),
        ('3rd Seat', 'w,w/o', 'null', 'XR3シート,XQ2乗心地性能,XL4シート', 'DRIVER SEAT', 'X03_SEAT'),
        ('CENTER CONSOLE', 'ALL', 'null', 'XX4EMC', 'DRIVER SEAT', 'X03_SEAT'),
        ('DR HEATED SEAT', 'w,w/o', 'null', 'XX4SC', 'DRIVER SEAT', 'X03_SEAT'),
        ('DR SEAT COMFORT FEATURE', 'ALL', 'null', 'XX4EMC', 'DRIVER SEAT', 'X03_SEAT'),
        ('DR SEAT HEATER AND COOLER', 'ALL', 'null', 'XX4EMC', 'DRIVER SEAT', 'X03_SEAT'),
        ('DR SEAT TYPE AND ADJUSTMENT', 'ALL', 'null', 'XX4EMC', 'DRIVER SEAT', 'X03_SEAT'),
        ('DR SEAT TYPE AND ADJUSTMENT.', 'POWER,MANUAL', 'null', 'XR6シートベルト', 'DRIVER SEAT', 'X03_SEAT'),
        ('Fr Heater Seat', 'with', 'null', 'XR5空調', 'DRIVER SEAT', 'X03_SEAT'),
        ('FR SEAT HEATER', 'Ｗ', 'null', 'XX4WH', 'DRIVER SEAT', 'X03_SEAT'),
        ('FR SEAT HEATER AND COOLER', 'Ｗ', 'null', 'XX4WH', 'DRIVER SEAT', 'X03_SEAT'),
        ('Fr 空調シート(Heater ＋ Cooler Seat)', 'with', 'null', 'XR5空調', 'DRIVER SEAT', 'X03_SEAT'),
        ('FRONT SEATS TYPE', 'ALL', 'null', 'XX4EMC,XR2車体信頼', 'DRIVER SEAT', 'X03_SEAT'),
        ('MASSAGE STANDARD\n(2nd seat)', 'w', 'null', 'XX4SPCU', 'DRIVER SEAT', 'X03_SEAT'),
        ('MASSAGE STANDARD\n(3rd seat)', 'w', 'null', 'XX4SPCU', 'DRIVER SEAT', 'X03_SEAT'),
        ('MASSAGE STANDARD\n(FR seat)', 'w', 'null', 'XX4SPCU', 'DRIVER SEAT', 'X03_SEAT'),
        ('POWER SEAT', 'w,w/o', 'null', 'XX4GN1ラジオノイズ', 'DRIVER SEAT', 'X03_SEAT'),
        ('Seat adjustment', 'メモリーあり,メモリーなし', 'null', 'XX4BCM', 'DRIVER SEAT', 'X03_SEAT'),
        ('SEAT HEATER', 'w,w/o', 'null', 'XX4GN1ラジオノイズ,XR6乗員判別', 'DRIVER SEAT', 'X03_SEAT'),
        ('SEAT HEATING', 'ALL', 'null', 'XX4EMC', 'DRIVER SEAT', 'X03_SEAT'),
        ('SEAT TYPE', '手動、自動', 'null', 'XQ5保安防災', 'DRIVER SEAT', 'X03_SEAT'),
        ('TYPE OF DRIVER SEAT ADJUS', 'ALL', 'null', 'XX4EMC', 'DRIVER SEAT', 'X03_SEAT'),
        ('Ventilated(Heater&Cooler) Seat', 'w,w/o', 'null', 'XR6乗員判別', 'DRIVER SEAT', 'X03_SEAT'),
        ('オットマン', 'ｗ', 'null', 'XL4シート', 'DRIVER SEAT', 'X03_SEAT'),
        ('シート機構', '8WP,6WM,4WP,4WM', 'null', 'XL4シート', 'DRIVER SEAT', 'X03_SEAT'),
        ('スポーツシート', 'null', 'null', 'XR3シート', 'DRIVER SEAT', 'X03_SEAT'),
        ('スライドシート', 'null', 'null', 'XR3シート', 'DRIVER SEAT', 'X03_SEAT'),
        ('空調シート', 'w', 'null', 'XR3シート,XL4シート', 'DRIVER SEAT', 'X03_SEAT'), (
            'Driving mode', 'LINタイプ,ハードウェアタイプ', 'どちらか不明、自動車のボディ制御に使われる通信プロトコル「LIN」', 'XX4BCM', 'DRIVING MODE',
            'X09_MECHANISM'), ('DRIVING MODE 2WD', 'ALL', 'null', 'XX4EMC', 'DRIVING MODE', 'X09_MECHANISM'),
        ('DRIVING MODE 4WD', 'ALL', 'null', 'XX4EMC', 'DRIVING MODE', 'X09_MECHANISM'),
        ('DRIVING MODE CONTROL', 'ALL', 'null', 'XX4EMC', 'DRIVING MODE', 'X09_MECHANISM'),
        ('ECONOMIC DRIVING', 'ALL', 'null', 'XX4EMC', 'DRIVING MODE', 'X09_MECHANISM'),
        ('EV SOUND FOR PEDESTRIANS', 'ALL', 'null', 'XX4EMC', 'EV DEDICATED FEATURES', 'X14_EV_PHEV_HEV'),
        ('ONE PEDAL FUNCTION WITH STOP', 'ALL', 'null', 'XX4EMC', 'EV DEDICATED FEATURES', 'X14_EV_PHEV_HEV'),
        ('GEAR SHIFT AT', 'ALL', 'null', 'XX4EMC', 'GEAR SHIFT', 'X02_COCKPIT'),
        ('GEAR SPEED CONTROL TYPE', 'ALL', 'null', 'XX4EMC', 'GEAR SHIFT', 'X02_COCKPIT'),
        ('ギアシフト', 'Shift by wire,コラムシフト', 'null', 'XX4BCM', 'GEAR SHIFT', 'X02_COCKPIT'),
        ('Auto Wiper', 'w,w/o', 'null', 'XX4BCM', 'GLASSES', 'X01_VISIBILITY'),
        ('FRONT WINDSCREEN HEATER', 'w,w/o', 'null', 'XX4GN1ラジオノイズ', 'GLASSES', 'X01_VISIBILITY'),
        ('FRONT WINDSCREEN HEATER / HEATED FRONT SCREEN', 'w,w/o', 'null', 'XM6アンテナ', 'GLASSES', 'X01_VISIBILITY'),
        ('FRONT WINDSCREEN WIPER SP', 'ALL', 'null', 'XX4EMC', 'GLASSES', 'X01_VISIBILITY'),
        ('HEATED SCREEN', 'Ｗ', 'null', 'XX4WH', 'GLASSES', 'X01_VISIBILITY'),
        ('Heating windscreen', 'w,w/o', 'null', 'XX4BCM', 'GLASSES', 'X01_VISIBILITY'),
        ('RAIN SENSITIVE', 'w,w/o', 'null', 'XX4オートライト,レインセンサ', 'GLASSES', 'X01_VISIBILITY'),
        ('REAR SCREEN', 'DEFOGGER', 'null', 'XX4EMC', 'GLASSES', 'X01_VISIBILITY'),
        ('REAR SCREEN SF', 'DEFOGGER', 'null', 'XX4EMC', 'GLASSES', 'X01_VISIBILITY'),
        ('REAR SCREEN WIPER', 'ALL', 'null', 'XX4EMC', 'GLASSES', 'X01_VISIBILITY'),
        ('REAR WINDOW', 'W/ TIMER', 'null', 'XX4EMC', 'GLASSES', 'X01_VISIBILITY'),
        ('REAR WINDOW WIPER', 'ALL', 'null', 'XX4EMC', 'GLASSES', 'X01_VISIBILITY'),
        ('REAR WIPERS\nリアワイパー', 'null', 'null', 'XR6視界', 'GLASSES', 'X01_VISIBILITY'),
        ('WINDOWS COLOUR', ' WIPER DE-ICER', 'null', 'XX4EMC', 'GLASSES', 'X01_VISIBILITY'),
        ('WINDSCREEN', ' WIPER DE-ICER,HEATING WINDSCREEN', 'null', 'XX4EMC', 'GLASSES', 'X01_VISIBILITY'),
        ('WINDSCREEN HEATER', 'ALL', 'null', 'XX4EMC', 'GLASSES', 'X01_VISIBILITY'),
        ('WINDSCREEN WIPERS\nフロントワイパー', 'null', 'null', 'XR6視界', 'GLASSES', 'X01_VISIBILITY'),
        ('WINDSCREEN WIPERS', 'ALL', 'null', 'XX4EMC', 'GLASSES', 'X01_VISIBILITY'),
        ('WIPER DEICER', 'Ｗ', 'null', 'XX4WH', 'GLASSES', 'X01_VISIBILITY'),
        ('ワイパーデアイサー', 'null', 'ワイパーの部分の電熱線が温まり、凍っていたワイパーが動くようになる', 'XR6視界', 'GLASSES', 'X01_VISIBILITY'),
        ('IN-CAR COMMUNICATION', 'ALL', 'null', 'XX4EMC', 'HMI', 'X02_COCKPIT'),
        ('OUTSIDE TEMPERATURE METER', 'ALL', 'null', 'XX4EMC', 'HMI', 'X02_COCKPIT'),
        ('OUTSIDE THERMO METER', 'ALL', 'null', 'XX4EMC', 'HMI', 'X02_COCKPIT'),
        ('VOICE VEHICLE CONTROL', 'ALL', 'null', 'XX4EMC', 'HMI', 'X02_COCKPIT'),
        (' HIGH BEAM ASSIST (HBA)', 'null', 'null', 'XR6視界', 'LIGHTING', 'X01_VISIBILITY'),
        ('3RD BRAKE LIGHT / HIGH MOUNT STOP LAMP', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('ADAPTIVE FRONT LIGHTING SYSTE(AFS)', 'w', 'null', 'XX4AFS', 'LIGHTING', 'X01_VISIBILITY'),
        ('ADB(ADAPTIVE DRIVING BEAM)', 'ｗ,w/o', 'null', 'XX4HBA,XX4ADB', 'LIGHTING', 'X01_VISIBILITY'),
        ('ADJUSTMENT OF HEADLIGHTS ', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('ALS(Auto Light Sensor)', 'w,w/o', 'null', 'XX4レインセンサ', 'LIGHTING', 'X01_VISIBILITY'),
        ('AUTO EXTENTION LIGHT ', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('Auto light', 'w/o,LINタイプ,ハードウェアタイプ', '自動車のボディ制御に使われる通信プロトコル「LIN」', 'XX4BCM', 'LIGHTING',
         'X01_VISIBILITY'),
        ('AUTO LIGHT (ALS)', 'w,w/o', 'null', 'XX4オートライト', 'LIGHTING', 'X01_VISIBILITY'),
        ('AUTO LIGHT SYSTEM', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('AUTO WIPER AND AUTO LIGHT', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('Brake lamp', 'LED,Bulb', 'null', 'XX4BCM', 'LIGHTING', 'X01_VISIBILITY'),
        ('BULB REAR LAMP', 'w', 'null', 'XX4GN1ラジオノイズ', 'LIGHTING', 'X01_VISIBILITY'),
        ('DAYTIME HEADLIGHTS', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('DAYTIME RUNNING LIGHT', 'with', 'null', 'XX7USM', 'LIGHTING', 'X01_VISIBILITY'),
        ('DAYTIME RUNNING LIGHT (DRL)', 'w,ALL', 'null', 'XR6視界,XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('DAYTIME RUNNING LIGHTS', 'ALL', 'null', 'XX4EMC,XX4WH', 'LIGHTING', 'X01_VISIBILITY'),
        ('Delay Timer', 'w,w/o', 'null', 'XX4BCM', 'LIGHTING', 'X01_VISIBILITY'),
        ('DRL', 'w,w/o', 'null', 'XX4BCM', 'LIGHTING', 'X01_VISIBILITY'),
        ('FOG LIGHTS', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('FR FOG LAMP', 'W', 'null', 'XL7外装', 'LIGHTING', 'X01_VISIBILITY'),
        ('FR FOG LAMP(HAROGEN)', 'W', 'null', 'XX4WH', 'LIGHTING', 'X01_VISIBILITY'),
        ('FR FOG LAMP(LED)', 'W', 'null', 'XX4WH', 'LIGHTING', 'X01_VISIBILITY'),
        ('Front Fog', 'w,w/o', 'null', 'XX4BCM', 'LIGHTING', 'X01_VISIBILITY'),
        ('FRONT FOG LAMP\nフロントフォグランプ', 'null', 'null', 'XR6視界', 'LIGHTING', 'X01_VISIBILITY'),
        ('FRONT FOG LAMP', 'LED,HALOGEN,w,all', 'null', 'XX7USM,XX4GN1ラジオノイズ,XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('FRONT ILLUMINATION LIGHT', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('FRONT LIGHT\nヘッドランプ', 'null', 'null', 'XR6視界', 'LIGHTING', 'X01_VISIBILITY'),
        ('FRONT LIGHT', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('FRONT LIGHT/HEAD LAMP', 'ALL', 'null', 'XX4WH', 'LIGHTING', 'X01_VISIBILITY'),
        ('GLARE FREE HIGH BEAM STANDARD / ADAPTIVE DRIVING BEAM (ADB)', 'w/o', 'null', 'XX4AFS', 'LIGHTING',
         'X01_VISIBILITY'),
        ('GROUND ILLUMINATION', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('HALOGEN HEADLAMP', 'w', 'null', 'XX4GN1ラジオノイズ', 'LIGHTING', 'X01_VISIBILITY'),
        ('HBA(HIGH BEAM ASSIST)', 'w/o,w', 'null', 'XX4ADB,XX4HBA', 'LIGHTING', 'X01_VISIBILITY'), (
            'HEAD LAMP LEVELIZER', 'Manual  LEVELIZER,AUTO   LEVELIZER,AirSUS LEVELIZER,ALL', 'null', 'XX7USM',
            'LIGHTING',
            'X01_VISIBILITY'), ('HEAD LAMPS TYPE', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('HEADLAMP CLEANER', 'with,ALL', 'null', 'XX7USM,XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('HEADLAMP TYPE', 'LED ,HALOGEN ', 'null', 'XX7USM', 'LIGHTING', 'X01_VISIBILITY'),
        ('HEADLIGHT WASHER', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('HEADLIGHT WIPERS', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('HIGH BEAM ASSIST', 'w,w/o', 'null', 'XX4GN1ラジオノイズ,XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('HIGH BEAM ASSIST (HBA)', 'w', 'null', 'XX4LEDHead', 'LIGHTING', 'X01_VISIBILITY'),
        ('HIGH MOUNTED STOP LAMP', 'null', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('LED HEADLAMP', 'w', 'null', 'XX4GN1ラジオノイズ', 'LIGHTING', 'X01_VISIBILITY'),
        ('LED LB', 'w', 'null', 'XX4LEDHead', 'LIGHTING', 'X01_VISIBILITY'),
        ('LED REAR LAMP ', 'w', 'null', 'XX4GN1ラジオノイズ', 'LIGHTING', 'X01_VISIBILITY'),
        ('PUDDLE LAMP', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('RAISED BRAKE LIGHT', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('REAR  LAMP', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('Rear Fog', 'LED,Bulb,w/o', 'null', 'XX4BCM', 'LIGHTING', 'X01_VISIBILITY'),
        ('REAR FOG LAMP\nリアフォグランプ', 'null', 'null', 'XR6視界', 'LIGHTING', 'X01_VISIBILITY'),
        ('REAR FOG LAMP', 'w,ALL', 'null', 'XX4GN1ラジオノイズ,XX4WH,XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('REAR LIGHT\nリアライト\nリアコンビランプ', 'null', 'null', 'XR6視界', 'LIGHTING', 'X01_VISIBILITY'),
        ('REAR LIGHT', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('RLS(Rain Light Sensor)', 'w,w/o', 'null', 'XX4オートライト,レインセンサ', 'LIGHTING', 'X01_VISIBILITY'),
        ('RR FOG LAMP', 'W', 'null', 'XL7外装', 'LIGHTING', 'X01_VISIBILITY'),
        ('SIDE LIGHTS', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('SIDE MARKER LAMP', 'ALL', '前後フェンダーの標識ランプ', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('SIDE TURN SIGNAL', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('TURN SIGNAL', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('TURN SIGNAL LAMP', 'ALL', 'null', 'XX4EMC', 'LIGHTING', 'X01_VISIBILITY'),
        ('コーナリングランプ', 'null', 'null', 'XR6視界', 'LIGHTING', 'X01_VISIBILITY'),
        ('フロントサイドマーカ', 'null', 'null', 'XR6視界', 'LIGHTING', 'X01_VISIBILITY'),
        ('ヘッドランプウオッシャー\n（HLC)', 'null', 'null', 'XR6視界', 'LIGHTING', 'X01_VISIBILITY'),
        ('リヤサイドマーカー', 'null', 'null', 'XR6視界', 'LIGHTING', 'X01_VISIBILITY'), (
            '外装イルミランプ', 'Coutesy lamp,Puddle lamp,w/o', 'ドアの開閉に伴って点灯・消灯し、乗降者の足元を照らす', 'XX4BCM',
            'LIGHTING',
            'X01_VISIBILITY'), ('足元ランプ（ミラー付け）', 'null', 'null', 'XR6視界', 'LIGHTING', 'X01_VISIBILITY'),
        ('Illumination BI', 'null', 'null', 'XL7外装', 'LOGO & EMBLEM', 'X08_EXTERIOR'),
        ('ACTIVE SOUND CONTROL', 'ALL', 'null', 'XQ4実車', 'NVH MANAGEMENT', 'X07_AUDIO_NAVIGATION_CCS'),
        ('ANC', 'ALL', 'null', 'XQ4実車', 'NVH MANAGEMENT', 'X07_AUDIO_NAVIGATION_CCS'),
        ('ANC (ACTIVE NOISE CANCELLATION)', 'ALL', 'null', 'XX4EMC', 'NVH MANAGEMENT', 'X07_AUDIO_NAVIGATION_CCS'), (
            'ANC / ACTIVE NOISE CANCELLATION / DRIVING SOUND CONTROL', 'ALL', 'null', 'XM6音質', 'NVH MANAGEMENT',
            'X07_AUDIO_NAVIGATION_CCS'), ('AUTO CLOSER', 'ｗ', 'null', 'XX4バックドアクロージャ―', 'OPENING', 'X08_EXTERIOR'),
        ('E-DIMMING', 'null', 'null', 'XX4Sunroof', 'OPENING', 'X08_EXTERIOR'),
        ('ELECTRICAL SIDE DOOR OPENING AND CLOSING', 'ALL', 'null', 'XX4EMC', 'OPENING', 'X08_EXTERIOR'),
        ('HAND FREE', 'w', 'Kick Sensor', 'XX4KickSensor', 'OPENING', 'X08_EXTERIOR'),
        ('Kick Sensor', 'w,w/o', 'null', 'XX4BCM', 'OPENING', 'X08_EXTERIOR'),
        ('PBD', 'w,w/o', 'Power Back Door', 'XX4BCM', 'OPENING', 'X08_EXTERIOR'),
        ('POWER BACK DOOR', 'w,w/o', 'null', 'XX4GN1ラジオノイズ,XX4WH,XR3ドアクロ', 'OPENING', 'X08_EXTERIOR'),
        ('Power Back Door(PBD)', 'w', 'null', 'XX4メカトロS46', 'OPENING', 'X08_EXTERIOR'),
        ('Power Slide Door', 'null', 'null', 'XR3ドアクロ', 'OPENING', 'X08_EXTERIOR'),
        ('Power Trunk', 'null', 'null', 'XR3ドアクロ', 'OPENING', 'X08_EXTERIOR'),
        ('REAR DOOR OPENING', 'ALL', 'null', 'XX4EMC', 'OPENING', 'X08_EXTERIOR'),
        ('REAR GATE OPENING', 'ALL', 'null', 'XX4EMC', 'OPENING', 'X08_EXTERIOR'),
        ('ROOF', 'ALL', 'null', 'XQ4実車', 'OPENING', 'X08_EXTERIOR'),
        ('ROOF / SUNROOF', 'ALL,Sun Roof,Glass Roof,Normal Roof', 'null', 'XX4EMC,XR6乗員判定', 'OPENING',
         'X08_EXTERIOR'),
        ('ROOF OPENING', 'Sun Roof,Glass Roof,Normal Roof', 'null', 'XR2車体信頼', 'OPENING', 'X08_EXTERIOR'), (
            'SUNROOF', 'null', 'null', 'XR3ドアクロ,XR5風音,XQ5保安防災,XX4ALARM,XX4BCM,XX4WH,XR6乗員判別', 'OPENING',
            'X08_EXTERIOR'),
        ('Sunshade', 'E-sunshade,basic,w/o', 'null', 'XX4BCM', 'OPENING', 'X08_EXTERIOR'),
        ('TAILGATE/TRUNK OPENING\nPOWER OPEN/CLOSE', 'w', 'null', 'XX4PBD', 'OPENING', 'X08_EXTERIOR'),
        ('TAILGATE/TRUNK OPENING', 'ALL', 'null', 'XX4EMC', 'OPENING', 'X08_EXTERIOR'),
        ('TAILGATE/TRUNK OPENING POWER OPEN/CLOSE', 'w,w/o', 'null', 'XX4GN1ラジオノイズ,XX4WH,XR3ドアクロ', 'OPENING',
         'X08_EXTERIOR'),
        ('TAILGATE/TRUNK OPENING POWER OPEN/CLOSE ✚ HANDS FREE', 'w,w/o', 'null', 'XX4GN1ラジオノイズ,XX4WH,XR3ドアクロ',
         'OPENING',
         'X08_EXTERIOR'), ('サンルーフ', 'w', 'null', 'XD2材料', 'OPENING', 'X08_EXTERIOR'),
        ('HORN', 'null', 'null', 'XR6視界', 'OTHER', 'X12_OTHER'),
        ('UNIVERSAL GARAGE DOOR OPE', 'ALL', 'null', 'XX4EMC', 'OTHER', 'X12_OTHER'),
        ('UNIVERSAL GARAGE DOOR OPENER', 'w,w/o', 'null', 'XX4GN1ラジオノイズ', 'OTHER', 'X12_OTHER'),
        ('ELECTRIC PARKING BRAKE', 'null', 'null', 'XQ5保安防災', 'PARKING BRAKE', 'X02_COCKPIT'),
        ('EPKB', 'null', 'null', 'XR2コントロール', 'PARKING BRAKE', 'X02_COCKPIT'),
        ('PARKING BRAKE TYPE', 'null', 'mechanical, electric両方', 'XJBVDC', 'PARKING BRAKE', 'X02_COCKPIT'),
        ('PARKING BRAKE TYPE AND ASSIST', 'ALL', 'null', 'XX4EMC', 'PARKING BRAKE', 'X02_COCKPIT'),
        ('PKB hand,foot', 'null', 'null', 'XR2コントロール', 'PARKING BRAKE', 'X02_COCKPIT'),
        ('TYPE OF PARK BRAKE', 'ALL', 'null', 'XX4EMC', 'PARKING BRAKE', 'X02_COCKPIT'),
        ('金属製フットレスト', 'null', 'null', 'XR2コントロール', 'PEDALS AND FOOT-REST', 'X02_COCKPIT'),
        ('ENGINE START / POWER ON', 'ALL', 'null', 'XX4EMC', 'PHYSICAL SWITCHES', 'X02_COCKPIT'),
        ('ENGINE START TYPE', 'with,ALL', 'null', 'XX7USM,XX4EMC', 'PHYSICAL SWITCHES', 'X02_COCKPIT'),
        ('Start Engine  type', 'I-key,CKC', 'null', 'XX4BCM', 'PHYSICAL SWITCHES', 'X02_COCKPIT'),
        ('INSIDE MIRROR\nインサイドミラー', 'null', 'null', 'XR6視界', 'REAR VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('INTERIOR REAR VIEW MIRROR', 'ALL', 'null', 'XX4EMC', 'REAR VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('ROOM MIRROR', 'ALL', 'null', 'XX4EMC,XQ4実車', 'REAR VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('ROOM MIRROR / REAR VISIBILITY', 'ALL', 'null', 'XX4EMC,XQ4車体', 'REAR VIEW MIRROR / CAMERA',
         'X01_VISIBILITY'),
        ('ROOM MIRROR－AUTO DIMMING', 'w', 'null', 'XX4GN1ラジオノイズ', 'REAR VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('ROOM MIRROR－SMART REAR VIEW MIRROR', 'w', 'null', 'XX4GN1ラジオノイズ', 'REAR VIEW MIRROR / CAMERA',
         'X01_VISIBILITY'),
        ('SMART REAR VIEW MIRROR', 'ALL', 'null', 'XX4WH', 'REAR VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('SRVM', 'null', 'null', 'XR6視界,XX4SC,XM6camera,XM6アンテナ', 'REAR VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('リアアンダーミラー', 'null', 'null', 'XR6視界', 'REAR VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('リアカメラウオッシャー', 'null', 'null', 'XR6視界', 'REAR VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('2ND ROW SEAT BELT', 'ALL', 'null', 'XX4EMC,XR6シートベルト', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('2ND ROW SEAT BELT REMINDER', 'ALL', 'null', 'XX4EMC,XR6シートベルト', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('2ND ROW SEAT BELT REMINDER OCS', 'w.w/o', 'null', 'XR6シートベルト', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('3RD ROW SEAT BELT', 'ALL', 'null', 'XX4EMC,XR6シートベルト', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('3RD ROW SEAT BELT REMINDER', 'ALL', 'null', 'XX4EMC', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('ASSISTANT SEAT BELT', 'ALL', 'null', 'XX4EMC', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('FRONT SEAT BELT', 'ALL', 'null', 'XX4EMC,XR6シートベルト', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('FRONT SEAT BELT ADJUSTMEN', 'ALL', 'null', 'XX4EMC', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('FRONT SEAT BELT PRE-TENSIONER', 'ALL', 'null', 'XX4EMC', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('FRONT SEAT BELT PRETENSIONER', 'ALL', 'null', 'XX4EMC', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('FRONT SEAT BELT REMINDER', 'ALL', 'null', 'XX4EMC,XR6シートベルト', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('Lapプリテン装備', 'with,without', '運転席プリテンショナ', 'XR6シートベルト', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('REAR CNTER SEAT BELT', 'ALL', 'null', 'XX4EMC', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('REAR SEAT BELT PRETENSIONER', 'ALL', 'null', 'XX4EMC', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('REAR SEATS BELT', 'ALL', 'null', 'XX4EMC', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('SEAT BELT NOT SECURED WAR', 'ALL', 'null', 'XX4EMC', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('SEAT BELT REMINDER', 'ALL', 'null', 'XX4EMC', 'SEAT BELT', 'X11_SAFETY_SECURITY'), (
            '前席ELR仕様', 'LLA,LLD,PSB', 'Emergency Locking Retractorチャイルドシート用', 'XR6シートベルト', 'SEAT BELT',
            'X11_SAFETY_SECURITY'),
        ('後席プリテン装備', 'with,without', 'null', 'XR6シートベルト', 'SEAT BELT', 'X11_SAFETY_SECURITY'),
        ('Automatically folding mirror', 'w,w/o', 'null', 'XX4BCM', 'SIDE VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('EXTERIOR MIRRORS RETRACTI', 'ALL', 'null', 'XX4EMC', 'SIDE VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('EXTERIOR REAR VIEW MIRROR', 'ALL', 'null', 'XX4EMC', 'SIDE VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('OUTSIDE MIRROR\nアウトサイドミラー', 'null', 'null', 'XR6視界', 'SIDE VIEW MIRROR / CAMERA', 'X01_VISIBILITY'), (
            'OUTSIDE MIRROR',
            'Electrrical Adjustment + Manual Folding,Electrrical Adjustment + Manual Folding + Heated,Electrrical Adjustment + Manual Folding + Heated + Memory,Electrrical Adjustment + Automatically Folding,Electrrical Adjustment + Automatically Folding + Heated,Electrrical Adjustment + Automatically Folding + Reverse Dr & As side,Electrrical Adjustment + Automatically Folding + Heated + Reverse Dr & As side',
            'null', 'XX4EMC,XX4スイッチ', 'SIDE VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('OUTSIDE MIRROR ADJUST', 'ALL', 'null', 'XX4EMC', 'SIDE VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('OUTSIDE MIRROR MEMORY', 'w', 'null', 'XX4PMU', 'SIDE VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('直前直左鏡', 'null', 'サイドアンダーミラー', 'XR6視界', 'SIDE VIEW MIRROR / CAMERA', 'X01_VISIBILITY'),
        ('sound bubble', 'ALL', 'null', 'XM6音質', 'SOUND BUBBLE', 'X07_AUDIO_NAVIGATION_CCS'),
        ('SPARE WHEEL', 'w', 'null', 'XR2車体信頼', 'SPARE WHEEL', 'X10_WHEELS_&_TIRES'), ('AUDIO SYSTEM',
                                                                                           'BOSE,non-BOSE,Klipsch 24SP,Klipsch 14SP,Klipsch 12SP,SP Ω違い,CCS2.0 GAS,CCS2.0 non-GAS,DA2(CCS2 DA),A-IVI2 Ph1,CCS1.5 DA,LowDA (Plus),N18,P-IVI ST2.1/ST3.1\nA-IVI ST2.1/ST3.1',
                                                                                           'null', 'XX4HF-VR-ETC',
                                                                                           'SPEAKERS',
                                                                                           'X07_AUDIO_NAVIGATION_CCS'),
        ('BOSE', 'w,w/o', 'null', 'XX4GN1ラジオノイズ', 'SPEAKERS', 'X07_AUDIO_NAVIGATION_CCS'),
        ('BOSE SPEAKER', 'Ｗ', 'null', 'XX4WH', 'SPEAKERS', 'X07_AUDIO_NAVIGATION_CCS'),
        ('SPEAKER', 'ALL', 'null', 'XM6音質', 'SPEAKERS', 'X07_AUDIO_NAVIGATION_CCS'),
        ('COMBINATION SWITCH', 'ALL', 'null', 'XX4EMC', 'STEERING', 'X02_COCKPIT'),
        ('PADDLE Shift', 'w,w/o', 'null', 'XX4BCM', 'STEERING', 'X02_COCKPIT'),
        ('PADDLE SHIFT LEVER', 'w,ALL', 'null', 'XX4GN1ラジオノイズ,XX4EMC', 'STEERING', 'X02_COCKPIT'),
        ('POWER STEERING', 'ALL', 'null', 'XX4EMC', 'STEERING', 'X02_COCKPIT'),
        ('PS', 'With', 'null', 'XQ2操安', 'STEERING', 'X02_COCKPIT'),
        ('STEERING', 'ELECTRIC POWERED', 'null', 'XX4EMC', 'STEERING', 'X02_COCKPIT'),
        ('STEERING SWITCH', 'ALL', 'null', 'null', 'STEERING', 'X02_COCKPIT'),
        ('STEERING SWITCHES', 'ALL', 'null', 'XX4EMC', 'STEERING', 'X02_COCKPIT'),
        ('STEERING WHEEL', 'ALL', 'null', 'XQ4実車', 'STEERING', 'X02_COCKPIT'),
        ('STEERING WHEEL ADJUSTMENT', 'ALL', 'null', 'XX4EMC,XQ4車体', 'STEERING', 'X02_COCKPIT'),
        ('STEERING WHEEL HEATER', 'ALL', 'null', 'XX4EMC,XX4WH', 'STEERING', 'X02_COCKPIT'),
        ('STRG Heater', 'w,w/o', 'null', 'XR5空調,XX4AD', 'STEERING', 'X02_COCKPIT'),
        ('VR', 'w,w/o', 'VOICE RECOGNITION ', 'XX4BCM', 'STEERING', 'X02_COCKPIT'),
        ('油圧PS(パワステ)', 'w', 'null', 'XQ4機構,XR5冷熱', 'STEERING', 'X02_COCKPIT'),
        ('ＳＴＲＧ固定式パドル', 'null', 'null', 'XR2コントロール', 'STEERING', 'X02_COCKPIT'),
        ('SUN VISOR LED LIGHT', 'w,w/o', 'null', 'XR6内外装', 'SUN VISOR', 'X02_COCKPIT'),
        ('TIRE', 'null', 'null', 'XJBVDC,XX4ALARM,XQ2操安', 'TIRES', 'X10_WHEELS_&_TIRES'),
        ('TIRE PRESSURE MONITOR', 'ALL', 'null', 'XX4EMC', 'TIRES', 'X10_WHEELS_&_TIRES'),
        ('TIRE PRESSURE MONITORING SYSTEM (TPMS)', 'ALL', 'null', 'XX4EMC', 'TIRES', 'X10_WHEELS_&_TIRES'),
        ('TIRE SIZE', 'null', 'null', 'XQ5保安防災', 'TIRES', 'X10_WHEELS_&_TIRES'),
        ('TIRE TYPE', 'null', 'null', 'null', 'TIRES', 'X10_WHEELS_&_TIRES'),
        ('TYPE OF TIRES FR', 'ALL', 'null', 'XR2車体信頼', 'TIRES', 'X10_WHEELS_&_TIRES'),
        ('TYPE OF TIRES RR', 'ALL', 'null', 'XR2車体信頼', 'TIRES', 'X10_WHEELS_&_TIRES'),
        ('SEAT LINING', 'ALL', 'null', 'XR6乗員判別,XQ4実車', 'TRIM', 'X03_SEAT'), (
            'SEAT LINING.', 'PUBLIC,SYNTHETIC LEATHER A,SYNTHETIC LEATHER B,SYNTHETIC LEATHER C', 'null', 'XR6シートベルト',
            'TRIM',
            'X03_SEAT'), ('シート材質', 'Cloth,Leather', 'null', 'XR3シート,XX4ALARM,XD2材料', 'TRIM', 'X03_SEAT'),
        (' POWER OPEN/CLOSE SLIDE', 'w', 'null', 'XX4PSD', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('3RD ROW SEAT HEATER AND COOLER', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('AC INV\n(V2L_inside)', 'w', 'null', 'XP4充電', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('AC-INV', 'ｗ', 'null', 'XP4EVシステム', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('Accel Pedal KD(キックダウン)', 'null', 'null', 'XR2コントロール', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ADDITIONAL HEATER FOR PASSENGERS', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ADDITIONAL REAR AIR CONDITIONING', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ASL', 'w', 'null', 'UE2動力運転性,XP4EVシステム', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ATシフトデバイス', 'null', 'アクセルペダルを踏み込んだ時のクリック感（踏みすぎ防止）', 'XR2コントロール', 'UNKNOW_device',
         'UNKNOW_device_group'),
        ('AUDIO VISUAL', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('AUTO COMPASS', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('AUTO LEVELIZER', 'null', 'null', 'XR6視界', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('BD-EPS(ベルトドライブEPS)', 'null', 'null', 'XQ4機構', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('BLACK BOX', 'W/ EVENT DATA RECORDER', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('Brake type', 'null', 'null', 'XJBVDC,XQ2VDC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('CAB違い', 'null', 'null', 'XQ2VDC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('CHARGE WARNING LAMP', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('CLUTCH CONTROL TYPE', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('CLUTCH_UNIT', 'null', 'null', 'XR2コントロール', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('COLD STARTING ASSISTANCE', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('Cross bar', 'null', 'null', 'XR5風音', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('DAS', 'w,w/o', 'DAS(ダイレクトアダプティブステアリング)', 'XQ5Failsafe', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('DAS(ダイレクトアダプティブステアリング)', 'null', 'null', 'XQ4機構', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('DCDC', 'ALL', 'null', 'XX4NH電動車', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('DIRECT ADAPTIVE STEERING', 'ｗ', 'null', 'XX4PT', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('DP-EPS(デュアルピニオンEPS)', 'null', 'null', 'XQ4機構', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('DRIVING ASSISTANCE', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('DYNAMIC TURN INDICATOR', 'w', 'null', 'XX4TurnLamp', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('e-releace', 'w', 'null', 'XX4メカトロS45', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ECO DRIVING COACHING', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ECU付電動センサーストレージボックス', 'ALL', 'null', 'XX4MCS', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ELECTRIC TOLL COLLECTION', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('EMERGENCY STOP SIGNAL ', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ENERGY SMART MANAGEMENT', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ENG', 'Gasoline,Diesel', 'null', 'XR2燃料', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ENGINE REV COUNTER', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ESCL', 'w,w/o', '電子ステアリング コラム ロック', 'XX4BCM', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ETC 2.0(ELECTRIC TOLL COLLECTION)', 'Ｗ', 'null', 'XX4WH', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('EV CHARGE CONN TYPE', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('EVSE', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('Exh.仕様', 'ALL', 'null', 'XR5冷熱', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('FR BMPR-type', 'ALL', 'null', 'XR6内外装', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('FR Grill-type', 'ALL', 'null', 'XR6内外装', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('FR SUSP形式違い', 'ALL', 'null', 'XQ5保安防災', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('FR:Multi\nRR:5link', 'w', 'null', 'XR2シャシー', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('FR:Multi\nRR:LEAF', 'w', 'null', 'XR2シャシー', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('FR:Multi\nRR:QI2', 'w', 'null', 'XR2シャシー', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('FR:STRUT\nRR:3Link', 'w', 'null', 'XR2シャシー', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('FR:STRUT\nRR:HT Beam', 'w', 'null', 'XR2シャシー', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('FR:STRUT\nRR:Prarell', 'w', 'null', 'XR2シャシー', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('FR:STRUT\nRR:QI2', 'w', 'null', 'XR2シャシー', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('FR:STRUT\nRR:RM2', 'w', 'null', 'XR2シャシー', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('FR:STRUT\nRR:TC', 'w', 'null', 'XR2シャシー', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('HANDS FREE POWER DOOR', 'w', 'null', 'XX4PSD', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('HDC', 'w', 'null', 'XQ2VDC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('HEPS(油圧電動パワステ)', 'null', 'null', 'XQ4機構', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('HEV/PHEV ENERGY MODE', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('Hood visor', 'null', 'null', 'XR5風音', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('IDM(ｲﾝﾃﾘｼﾞｪﾝﾄ ﾀﾞｲﾅﾐｸｽｺﾝﾄﾛｰﾙ ﾓｼﾞｭｰﾙ)', 'null', 'null', 'XQ4機構', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('IONIZER', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('IVC', 'null', 'null', 'XX4リモート', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('KEY SET', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('LIGHTS-ON WARNING', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('LUGGAGE HOOK', 'ｗ', 'null', 'XR2車体信頼', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('MANUAL LEVELIZER', 'null', 'null', 'XR6視界', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('MAP LAMP', 'w,w/o', 'null', 'XR6内外装', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('Max C.W.\nFR', 'ｗ', 'null', 'XR2車体信頼', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('Max C.W.\nRR', 'ｗ', 'null', 'XR2車体信頼', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('Max C.W.\nTotal', 'ｗ', 'null', 'XR2車体信頼', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('MEDIA', 'AM/FM,DTV,SXM,DAS', 'null', 'XM6アンテナ', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('MICROPHONE', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('MUD GUARD', 'w,w/o', 'null', 'XR6内外装', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('OFF ROAD', 'ALL', 'null', 'XX4EMC,XQ2操安', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('PATH CONTROL', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('PCU', 'null', 'null', 'XX4リモート', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('POWER OPEN/CLOSE SLIDE', 'w', 'null', 'XX4メカトロS45', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('PRE CRASH', 'w', 'null', 'XX4プリクラッシュ', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('REAR SPOILER', 'w,w/o', 'null', 'XR6内外装', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('REAR TOWING DEVICE', 'ｗ', 'null', 'XR2車体信頼', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('REGENERATIVE BRAKE FOR EV', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('REGENERATIVE BRAKING TYPE', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('REMOTE ENGINE STARTER', 'w,w/o', 'null', 'XX4BCM,XX4GN1ラジオノイズ', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('REMOTE ENGINE STARTER (STAND ALONE)', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('REMOTE ENGINE STARTER WITH KEY', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('RES', 'ｗ', 'null', 'XP4EVシステム', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('Roof rack', 'null', 'null', 'XR5風音', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('Roof rail', 'w,w/o', 'null', 'XR5風音,XR6内外装', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ROOF RAIL AND CROSS BAR', 'ｗ', 'null', 'XR2車体信頼', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('RR BMPR-type', 'ALL', 'null', 'XR6内外装', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('RR POWER SLIDE  DOOR ', 'Ｗ', 'null', 'XX4WH', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('RR SPOILER', 'null', 'null', 'XL7外装', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('RR SUSP形式違い', 'ALL', 'null', 'XQ5保安防災', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('RVI CRUISE CONTROL', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('SEAT HEATER AND COOLER', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('Side visor', 'null', 'null', 'XR5風音', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('SP1', '2phm,4ohm', 'null', 'XM6音質', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('SP2', 'Bose,Klipsch,Panasonic,6SP,4SP,2SP', 'null', 'XM6音質', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('SPEED CUT', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('STATIONARY HEATER', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('Sunroof visor', 'null', 'null', 'XR5風音', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('SUSPENSION CONTROL', 'null', 'null', 'XJBVDC', 'UNKNOW_device', 'UNKNOW_device_group'),
        (
            'SUSPENSION CONTROL VARIABLE DAMPING', 'w,w/o', 'null', 'XX4PT,XX4EMC', 'UNKNOW_device',
            'UNKNOW_device_group'),
        ('SUSPENSION TYPE', 'ALL', 'null', 'XQ5車両信頼性,XJBVDC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('TELEMATIC', 'w,w/o', 'null', 'XX4GN1ラジオノイズ', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('TELEMATIC DOORS LOCK', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('TELEMATIC SYSTEM HYPOTHES', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('TELEMATICS\n(EMERGENCY CALL SW)', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('TOWING CAPACITY', '最大仕様', 'null', 'XQE電動車,XR2車体信頼', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('TRACTION CONTROL SYSTEM', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('TRUNK', 'POWER OPEN/CLOSE', 'null', 'XX4PTL', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('TSA', 'w', 'null', 'XQ2VDC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('TYPE OF CONTROL', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('VEHICLE DYNAMICS CONTROL', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('WELCOME & GOODBYE SEQUENCE', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('WITH TIMER CHARGER', 'ALL', 'null', 'XX4EMC', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('アンダーカバー', 'null', 'null', 'XQ5保安防災', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ウィンドシールド取付構造', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ウィンドシールド形状', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ウインチ', 'null', 'winch', 'XQA商品性', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('エアバッグシステム', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('エネルギー\n吸収材仕様', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('エンジンフード形状', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('キャニスタ ORVR 追加', 'null', 'null', 'XQ5保安防災', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('グリルシャッター', 'null', 'null', 'XQ5保安防災', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('コラムEPS', 'null', 'null', 'XQ4機構', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('サスペンション', 'ALL', 'null', 'XX4ALARM', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('シル構造', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('シートベルトアンカ位置', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('センターピラー構造', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('トーイング', 'null', 'towing', 'XQA商品性,XQ2操安', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('バッテリクーラ', 'w', 'null', 'XP4充電', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('バッテリヒータ', 'w', 'null', 'XP4充電', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('バッテリー', 'AFD,HE', 'null', 'XX4ALARM', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('バンパ仕様', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('フィラーチューブ', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('フューエルタンクの取り付け方式', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('フューエルタンクの材質', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('フューエルタンク形状', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('フューエルタンク搭載位置', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('フロントサイドメンバ構造', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('フロントピラー構造', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('フロントフェンダ外形', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('フードヒンジ構造', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ヘッドランプ外形', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('マニュアルトランスミッション', 'null', 'null', 'XQA商品性', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('リア・サイド・メンバー / リア・サイド・フレームの形状', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ルーフサイド構造', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('ワイパ外形', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('乗員H.P.', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('内装違い', 'null', 'null', 'XQ5保安防災', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('冷却仕様', 'ALL', 'null', 'XR5冷熱', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('外装違い\nナロー/ワイド、2/3ROW', 'null', 'null', 'XQ5保安防災', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('姿勢違い', 'null', 'null', 'XQ5保安防災', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('強電BAT MD/Cell違い', 'null', 'null', 'XQ5保安防災', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('強電BAT 容量違い', 'null', 'null', 'XQ5保安防災', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('後輪懸架装置', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('燃料供給方式', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('燃料系部品取り付け構造', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('燃料配管', 'null', 'null', 'XR8XTF', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('跳ね上げフード', 'with,without', 'null', 'XR6歩行者保護', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('車体色', '黒若しくはダーク色', 'null', 'XD2材料', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('電装OPT', 'Full OPT,OPT無し', 'null', 'XX4AIO', 'UNKNOW_device', 'UNKNOW_device_group'),
        ('Alarm type', 'Perimeric,Volmatric', 'null', 'XX4BCM', 'WARNING & ALERT', 'X11_SAFETY_SECURITY'),
        ('ANTI-THEFT DEVICES', 'with,ALL', 'null', 'XX7USM,XX4EMC', 'WARNING & ALERT', 'X11_SAFETY_SECURITY'),
        ('AUTO HAZARD', 'null', 'null', 'XR6視界', 'WARNING & ALERT', 'X11_SAFETY_SECURITY'),
        ('DRIVER ATTENTION ALERT', 'ALL', 'null', 'XX4EMC,XQ3AD', 'WARNING & ALERT', 'X11_SAFETY_SECURITY'),
        ('EMERGENCY CALL AND BREAKDOWN', 'ALL', 'null', 'XX4EMC', 'WARNING & ALERT', 'X11_SAFETY_SECURITY'),
        ('EMERGENCY SIGNAL', 'ALL', 'null', 'XX4EMC', 'WARNING & ALERT', 'X11_SAFETY_SECURITY'),
        ('LEAD CAR DEPARTURE NOTIFICATION', 'ALL', 'null', 'XX4EMC', 'WARNING & ALERT', 'X11_SAFETY_SECURITY'),
        ('LEAD CAR DEPARTURE NOTIFICATION (LCDN)', 'ALL', 'null', 'XX4EMC', 'WARNING & ALERT', 'X11_SAFETY_SECURITY'),
        ('POST COLLISION AND BREAKDOWN', 'ALL', 'null', 'XX4EMC', 'WARNING & ALERT', 'X11_SAFETY_SECURITY'),
        ('Wheel Cover', 'with & 全種類', 'null', 'XR2シャシー', 'WHEELS & WHEEL COVERS', 'X10_WHEELS_&_TIRES'),
        ('WHEEL COVERS-size', 'ALL', 'null', 'XR6内外装', 'WHEELS & WHEEL COVERS', 'X10_WHEELS_&_TIRES'),
        ('WHEEL TYPE,SIZE', 'ALL', 'null', 'XQ4実車', 'WHEELS & WHEEL COVERS', 'X10_WHEELS_&_TIRES'),
        ('Wheelサイズ', 'ALL', 'null', 'XR2シャシー,XQ4車体', 'WHEELS & WHEEL COVERS', 'X10_WHEELS_&_TIRES'),
        ('Wheel材質', 'AL Wheel,Steel Wheel', 'null', 'XR2シャシー,XQ4車体', 'WHEELS & WHEEL COVERS', 'X10_WHEELS_&_TIRES'),
        ('FRONT  WINDOW OPENING SYS', 'ALL', 'null', 'XX4EMC', 'WINDOW OPENING', 'X02_COCKPIT'),
        ('FRONT DOOR WINDOW OPENING', 'ALL', 'null', 'XX4EMC', 'WINDOW OPENING', 'X02_COCKPIT'),
        ('FRONT DOOR WINDOW OPENING2',
         'POWERED FR WINDOW LIFT ✚ AUTO REVERSE ✚ DRIVER ONE TOUCH ✚ TIMER ✚ ALL WINDOW CONTROL PANEL',
         'null', 'XX4スイッチ',
         'WINDOW OPENING',
         'X02_COCKPIT'),
        ('Powerwindow', '4席アンチピンチあり, 4席アンチピンチなし', 'SPに4APと記載', 'XX4BCM', 'WINDOW OPENING', 'X02_COCKPIT'),
        ('REAR DOOR WINDOW OPENING', 'ALL', 'null', 'XX4EMC', 'WINDOW OPENING', 'X02_COCKPIT'), (
            'REAR DOOR WINDOW OPENING2', 'POWERED REAR WINDOW LIFT ✚ TIMER,POWERED REAR WINDOW LIFT', 'null', 'XX4スイッチ',
            'WINDOW OPENING', 'X02_COCKPIT'),
        ('REAR WINDOW OPENING SYSTE', 'ALL', 'null', 'XX4EMC', 'WINDOW OPENING', 'X02_COCKPIT'),
        ('TYPE OF DOOR-OPENER REMOT', 'ALL', 'null', 'XX4EMC', 'WINDOW OPENING', 'X02_COCKPIT')]

# Chuyển đổi list các tuple thành DataFrame tạm thời
"""
device_details_name = colD
option_detail = colC
auto = colA
group_detail = colB
device_name = sub_max
device_group = max
"""
#
df = pd.DataFrame(data, columns=['colD', 'colC', 'colA', 'colB', 'sub_max', 'max'])
df = df[['max', 'sub_max', 'colA', 'colB', 'colC', 'colD']]
df_sorted = df.sort_values(by=['max', 'sub_max'])
column_max_list = df_sorted.iloc[:, 0].tolist()
unique_list_max = list(set(column_max_list))
print("unique_list_max: ", unique_list_max)
column_submax_list = df_sorted.iloc[:, 1].tolist()
unique_list_submax = list(set(column_submax_list))
print("unique_list_submax: ", unique_list_submax)



result_tuple = [tuple(row) for row in df_sorted.to_records(index=False)]
# print(result_tuple)
# Danh sách để lưu trữ các giá trị của từng cột
col1 = []
col2 = []
col3 = []
col4 = []

# Xử lý dữ liệu để điền vào các danh sách
for row in result_tuple:
    col1.extend([row[0], row[1], row[2]])
    col2.extend(['', '', row[3]])
    col3.extend(['', '', row[4]])
    col4.extend(['', '', row[5]])

# Tạo DataFrame từ các danh sách
result_df = pd.DataFrame({
    'col1': col1,
    'col2': col2,
    'col3': col3,
    'col4': col4
})

# Tách các hàng có giá trị 'null' trong cột 'col1'
null_rows = result_df[result_df['col1'] == 'null']

non_null_rows = result_df[result_df['col1'] != 'null']
# print("non_null_rows:")
# print(non_null_rows)
# Loại bỏ các hàng trùng lặp từ phần không chứa 'null'
non_null_deduplicated = non_null_rows.drop_duplicates(subset=['col1'], keep='first')
# print("non_null_deduplicated: ")
# print(non_null_deduplicated)
# Kết hợp lại hai phần này
# result_df = pd.concat([null_rows, non_null_deduplicated]).reset_index(drop=True)
result_df = pd.concat([null_rows, non_null_deduplicated])
result_df = result_df.sort_index()
result_df = result_df.replace('null', None)
# print(result_df)
# print(result_df)
# df_x = result_df.drop_duplicates(subset=['col1'], keep='first')
# result_df.to_excel(r'C:\Users\KNT21617\Downloads\newken\project\data\processed\abc.xlsx', index=None)
# Đặt lại chỉ số (index)
# result_df.to_excel(r'C:\Users\KNT21617\Downloads\newken\project\data\processed\abcd.xlsx', index=None, header=None)
